// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM5s2feE8CunLxfYhcvSfSgguIbKUU_Zg',
    appId: '1:8401688697:ios:56948bc926396f39235ca8',
    messagingSenderId: '8401688697',
    projectId: 'nyiapp-3a612',
    databaseURL: 'https://nyiapp-3a612.firebaseio.com',
    storageBucket: 'nyiapp-3a612.appspot.com',
    androidClientId: '8401688697-bhp8miqvce66t9gqorej71h2djq4olqb.apps.googleusercontent.com',
    iosClientId: '8401688697-pesvv4f0vq36vi7lukk4nclqcormb2gk.apps.googleusercontent.com',
    iosBundleId: 'com.app.porelabBubblepoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2VIFancUpmnNcye0sjSe8NafvuhWDJUo',
    appId: '1:8401688697:web:ce9564b7d2c9447a235ca8',
    messagingSenderId: '8401688697',
    projectId: 'nyiapp-3a612',
    authDomain: 'nyiapp-3a612.firebaseapp.com',
    databaseURL: 'https://nyiapp-3a612.firebaseio.com',
    storageBucket: 'nyiapp-3a612.appspot.com',
  );
}
